name: Node.js CI

on:
  pull_request:
    branches: 
      - main

jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Use Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: '20.x'
  #     - run: npm ci
  #     - run: npm run build --if-present
  #     - run: npm test
  sonar:
    # needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        with:
          fetch-depth: 0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  docker-build-push:
    needs: [sonar]
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
  
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: beriloqueiroz/ci-test-fc-js:latest
